### ISSUE TITLE
Missing packages

### ISSUE THREAD

**Issue by silviubqualitance** [vmous/jToolbox#1]
In the SheetMusic.java there is an import:
import toolbox.design.patterns.creational.prototype.Note.Accidental;

There is no folder Note in the prototype folder.

I haven't checked all the code, there may be some other missing packages/files.

**Comment by vmous** [comment]
Hi Silviu,

thanks for your observation! Note is not a folder, is a class you can find lying in the same prototype folder of SheetMusic. Note.Helmhotz for example is an enumeration declared inside the Note class; that is why I have to deference it through its enclosing class. Do not think the dotted format of imports as a directory hierarchy, it is a namespace. Of course it happens also that the package part also maps to folders in the filesystem but do not generalize more than that :)

According to this
http://stackoverflow.com/questions/1677037/how-can-i-reference-my-java-enum-without-specifying-its-type
it looked that maybe the imports have to be static so I changed this and pushed.

If you also agree that this ticket can be considered closed please do so.
β

**Comment by silviubqualitance** [comment]
Hi Vassilis,

Thank you for the fast feedback. You are right, I haven't really paid attention to Note class. I will close it.

Good job, you have a very nice and helpful repository. I really enjoyed it last night.

One suggestion(I don't want another ticket for it): Can you simulate the Beans Factory from the Spring factory? I want to see how it works behind the doors.

Silviu

**Comment by vmous** [comment]
Hi Silviu,

glad that you found my repo useful!

I suggest for what you asked about the Bean Factory you open an "enhancement" ticket where you provide
- a small description of your request,
- link to some extra material, like the API page of an implementation of this design pattern you are asking for (you said it is part of the Spring Framework?).

The above will help me have a concrete starting point. The only thing I cannot guarantee, though, is my response because this period I'm really lacking of time...

Thanks and all the best,
β
